### ISSUE TITLE
build: create a unified environment/config file

### ISSUE THREAD

**Issue by cabreraalex** [Sparkier/zeno_hub#72]
There are a bunch of settings for both the frontend and backend spread out between .env, database.ini, and other files. 

Would be nice to have some top-level configuration files (for dev, prod, etc.) everything could read from.

**Comment by Sparkier** [comment]
I agree we should probably make this easier, but those would probably need to be copied over to their individual files anyway if we want to keep using [SvelteKit's `env`](https://kit.svelte.dev/docs/modules#$env-dynamic-private). But should think about how this should be set up generally.

**Comment by Sparkier** [comment]
Could also make everything read from `frontend/.env` [like here](https://github.com/Sparkier/zeno_hub/blob/c557890637d7fe18739032b9c56d40c6bccac981/backend/zeno_backend/server.py#L64-L66) potentially if env variables are not set.

**Comment by cabreraalex** [comment]
Ah interesting yeah can maybe write out all the env variables that are set across the application at some point and where they live/where they have to be, then decide where to put them.

**Comment by cabreraalex** [comment]
Don't think this is as important with the new docker-compose setup.
